// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// emptyNumeric
SEXP emptyNumeric(int n);
RcppExport SEXP _emptyInit_emptyNumeric(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(emptyNumeric(n));
    return rcpp_result_gen;
END_RCPP
}
// emptyMatrix
SEXP emptyMatrix(int nrow, int ncol);
RcppExport SEXP _emptyInit_emptyMatrix(SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(emptyMatrix(nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_emptyInit_emptyNumeric", (DL_FUNC) &_emptyInit_emptyNumeric, 1},
    {"_emptyInit_emptyMatrix", (DL_FUNC) &_emptyInit_emptyMatrix, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_emptyInit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
